### PR TITLE
Remove whitespaces from start and end of urls

### PR DESCRIPTION
**Pull request by mehran-naghizadeh**
This PR seeks to make sure that urls don't contain any extra whitespaces.

### CODE REVIEW

**Comment by madnificent** [comment]
@mehran-naghizadeh This is nitpicking: do we need the trimStart on key-up?  I'd suppose trim on focus-out would be sufficient.  Did you experience a hickup with only focus-out?

**Comment by mehran-naghizadeh** [comment]
> @mehran-naghizadeh This is nitpicking: do we need the trimStart on key-up? I'd suppose trim on focus-out would be sufficient. Did you experience a hickup with only focus-out?

I have added the _key-up_ action for the sake of user experience. By having this action, users are prevented from starting a url with a whitespace. Should they ever try to start by a whitespace, the whitespace will be immediately removed. For the normal user it feels like there is some sort of intelligence behind the scenes.

**Comment by madnificent** [comment]
Makes sense.  I think it's covered by the focus-out though.  The `trim` function removes whitespace from the start and from the end.  That should be sufficient no?

**Comment by mehran-naghizadeh** [comment]
> Makes sense. I think it's covered by the focus-out though. The `trim` function removes whitespace from the start and from the end. That should be sufficient no?

As the name implies focus-out will take effect only when focus is changed. With the _focus-out_ action, user can type a url beginning with some whitespaces and then those whitespaces will be removed once the user clicks somewhere else, etc. On the other hand,  _key-press_ acts instantly. So, our user won't be able to start typing by whitespace. However, the choice is up to you.

**Comment by nvdk** [comment]
closing due to inactivity

**Pull request closed without merging**
